/** Slugify a theme name for use as a filename. */
function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

function serializePreset(preset: unknown): string {
  return JSON.stringify(
    preset,
    (_key, value) => (typeof value === 'function' ? undefined : (value as unknown)),
    2,
  );
}

/** Trigger a browser download of a theme preset as a standalone `usePreset()`-ready .ts file. */
export function downloadThemePreset(name: string, preset: unknown): void {
  const presetJson = serializePreset(preset);
  const fileName = `${slugify(name)}-preset.ts`;
  const origin = typeof window !== 'undefined' && window.location ? window.location.origin : '';
  const content = `/* eslint-disable */
// Generated by ${origin || 'Optimus UI Design'}
// Theme: ${name}

export default ${presetJson} as const;
`;

  const blob = new Blob([content], { type: 'text/typescript' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', fileName);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
